### ISSUE TITLE
Encoding is giving an error. 

### ISSUE THREAD

**Issue by wolass** [apetros/parse_bib#1]
Hi im getting an error while trying your script.

python version 2.7, newest bibtexparser.

```
Traceback (most recent call last):
  File "parse_bib.py", line 80, in <module>
    with open(inputfile, encoding="utf8") as bibtex_file:
TypeError: 'encoding' is an invalid keyword argument for this function
```

any ideas ?

**Comment by apetros** [comment]
I use python 3. You will need to change the open line to match python 2.7. Please check [this thread](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2).

Basically, you need to import the module io (import io) and replace the command "open" with "io.open".
