### ISSUE TITLE
Not parsing with Python 2.7 or Python 3

### ISSUE THREAD

**Issue by aaravrav142** [apetros/parse_bib#2]
Hi
I am trying your script with a bib file. I tried using both python3 and python 2.7 but cannot run the script: I am using on ubuntu 16.
My errors are as follows- With Python3 version 3.5 
```
$ python3 parse_bib.py -i myrefs.bib 
Traceback (most recent call last):
  File "parse_bib.py", line 12, in <module>
    import bibtexparser
ImportError: No module named 'bibtexparser'
```
However bibtexparser is already installed using the command `sudo pip install bibtexparser`. 
I also tried `python-bibtexparser` but same result. I
With Python2.7
```
$ python parse_bib.py -i myrefs.bib
Traceback (most recent call last):
  File "parse_bib.py", line 80, in <module>
    with open(inputfile, encoding="utf8") as bibtex_file:
TypeError: 'encoding' is an invalid keyword argument for this function

```
Can you help with this issue

**Comment by apetros** [comment]
Hi, I just tested and it works fine. I use Anaconda Python 3.7.2. I installed bibtexparser with pip and it executed without a problem.

It is not compatible to Python 2.

**Comment by aaravrav142** [comment]
Hi, 
Retested it with Python3 after compiling bibtexparser from source and it worked fine. Thanks a lot.
